# Generated by Django 3.2.18 on 2023-03-04 17:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='profile_default.jpeg', max_length=255, verbose_name='image'),
        ),
    ]
