# Generated by Django 3.2.18 on 2023-03-12 19:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
